[features]
seeds = false
skip-lint = false
[programs.localnet]
crowfunding = "8sxgrgtckSkTFmWhUZqqcogK43CLvwD7VAaT6wdDHYyC"

[registry]
url = "https://api.testnet.solana.com"

[provider]
cluster = "testnet"
wallet = "/Users/joshuabell/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
